name: Build .NET Framework Application
on:
  push:
    paths:
      - ".code/ChmlFrpLauncher-cs**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".code/ChmlFrpLauncher-cs/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Describe
        shell: bash
        run: |
          describe=`git describe --tags --always`
          echo "describe=$describe" >> $GITHUB_ENV

<<<<<<< HEAD
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild ".code\\ChmlFrpLauncher-cs.sln" -p:Configuration=${{ matrix.configuration }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }} ${{ env.describe }}
          path: .code\\ChmlFrpLauncher-cs\ChmlFrpLauncher-cs\bin\${{ matrix.configuration }}\ChmlFrpLauncher_cs.exe
=======
    - name: Build
      run: msbuild ".code\\ChmlFrpLauncher-cs.sln" -p:Configuration=${{ matrix.configuration }}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }} ${{ env.describe }}
        path: .code\ChmlFrpLauncher-cs\obj\Release\ChmlFrpLauncher_cs.exe
    
>>>>>>> eade637f55afeb09ab4c3db20521a7d49f3194d7
