name: Build .NET Framework Application

on:
  push:
    paths:
      - ".code/ChmlFrp_WPF_Clienter/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".code/ChmlFrp_WPF_Clienter/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Describe & Version
        shell: bash
        run: |
          describe=`git describe --tags --always`
          version=$(grep 'AssemblyVersion("' ".code/ChmlFrp_WPF_Clienter/Properties/AssemblyInfo.cs" | sed -E 's/.*AssemblyVersion\("([^"]+)".*/\1/')
          echo "describe=$describe" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild ".code\\ChmlFrp_WPF_Clienter.sln" -p:Configuration=${{ matrix.configuration }}

      - name: Move Executable to Root
        run: |
          Move-Item -Path .code\ChmlFrp_WPF_Clienter\bin\Release\ChmlFrp_WPF_Clienter.exe -Destination .\

      - name: Upload a Build Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.configuration }}-Pre-alpha${{ env.describe }}-${{ env.version }}-Windows
            path: |
             ChmlFrp_WPF_Clienter.exe
             README.md
             LICENSE.md
