name: Build .NET Framework Application

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore .code\ChmlFrpLauncher-cs.sln

      - name: Build and Publish WPF C# App
        run: msbuild .code\ChmlFrpLauncher-cs.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
