name: Build
on:
  push:
    paths:
      - '.code/ChmlFrpLauncher-cs**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.code/ChmlFrpLauncher-cs/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:  
       matrix:  
         configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set Describe
      shell: bash
      run: |
          describe=`git describe --tags --always`
          echo "describe=$describe" >> $GITHUB_ENV
          
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild ".code\\ChmlFrpLauncher-cs.sln" -p:Configuration=${{ matrix.configuration }}
